### ISSUE TITLE
 < > and MathJax

### ISSUE THREAD

**Issue by mennucc** [plastex/plastex#248] opened 2021-02-04 11:27 UTC
hi

if you compile this  ` $x<y$ or $x>y$` in current plastex, in the html output  you get exactly the same `$x<y$ or $x>y$`

but this is invalid in HTML, indeed this is rendered as `xy`

the attached patch fixes the problem

after you apply this patch, you will get `\(x{\lt}y\) or \(x{\gt}y\).` in the HTML, and this is fine, MathJax will render it correctly

the patch also works when the renderer is XHTML

[0007-fix-mathjax-change-and-in-lt-and-gt-add-macros-.txt](https://github.com/plastex/plastex/files/5925377/0007-fix-mathjax-change-and-in-lt-and-gt-add-macros-.txt)

**Comment by mennucc** [comment] 2021-02-04 11:33
this patch , as you see , also alters the delimiter for inline math; w/o the patch it is `$` dollars, with the patch it is `\(` 

this is good, indeed there is an option --dollars/--no-dollars, if the latter is selected, then MathJax will not rendere formulas enclosed in dollars; with my patch, you will see correctly rendered inline math nonetheless

in general,  IMHO using dollars for inline math is a bad habit, indeed it makes it difficult for an algorithm to parse , to see where a formula ends or begins, 

using `\(\)` is so a good idea

**Comment by mennucc** [comment] 2021-02-04 11:42
Let me be more precise with an example

try plastex on this: `This is a dollar \$ this is a cosine $\cos$ this is another \$`
(note that it is perfectly fine TeX)
the HTML will confuse MathJax utterly

now apply my patch and then use the command `plastex   --no-dollars   plastex_test.tex`
it works fine

so : you should apply my patch, and also make --no-dollars the default

**Comment by mennucc** [comment] 2021-02-04 11:49
Let me eventually note that my patch is not perfect, it can be fooled by this (admittetly wicked) example

` \textbackslash(x+y\textbackslash)`

this is compiled as text by `pdflatex` but is rendered as `\(x+y\)` in HTML, so that then MathJax will render it as a formula

I think this may be avoided by rendering `\textbackslash` as an entity , I did not test though

**Comment by PatrickMassot** [comment] 2021-04-05 15:29
This is a duplicate of #143.

**Closed by PatrickMassot** 2021-04-05 15:29 UTC
