### ISSUE TITLE
Bibliography problem

### ISSUE THREAD

**Issue by samtsevich** [plastex/plastex#234] opened 2020-11-11 21:50 UTC
Previously, I had a plastex built on the python2.7. But I made `git pull`, and I had to reinstall it, basing on the python3.8, which looks fine.
So, I was trying to run the following command:
`plastex file.tex`

And got a very long log with a very strange error related to the citation part:
```
plasTeX version 2.1
 (loading package /usr/local/lib/python3.9/site-
   packages/plasTeX/Packages/article.py
 )
 (loading package /usr/local/lib/python3.9/site-
   packages/plasTeX/Packages/graphicx.py
 )
 (loading package /usr/local/lib/python3.9/site-
   packages/plasTeX/Packages/color.py
 )
 (loading package /usr/local/lib/python3.9/site-
   packages/plasTeX/Packages/url.py
 )..
 (loading package /usr/local/lib/python3.9/site-
   packages/plasTeX/Packages/multicol.py
 )..
 (loading package /usr/local/lib/python3.9/site-
   packages/plasTeX/Packages/natbib.py
 )..
WARNING: No Python version of bibentry.sty was found
WARNING: Will now try to load a LaTeX implementation of bibentry.sty
 ( /usr/local/texlive/2020/texmf-dist/tex/latex/natbib/bibentry.sty )
WARNING: unrecognized command/environment: @ifstar
...........................................................................
.........................................................................
 (loading package /usr/local/lib/python3.9/site-
   packages/plasTeX/Packages/tocbibind.py
 )..
 (loading package /usr/local/lib/python3.9/site-
   packages/plasTeX/Packages/amsmath.py
 )
 (loading package /usr/local/lib/python3.9/site-
   packages/plasTeX/Packages/hyperref.py
 )..
 (loading package /usr/local/lib/python3.9/site-
   packages/plasTeX/Packages/listings.py
 )..................
 (loading package /usr/local/lib/python3.9/site-
   packages/plasTeX/Packages/fancyhdr.py
 )..... ( ./title_page.tex )..................... ( ./1_history_USPEX.tex )
...........................................................................
...........................................................................
....................... ( ./2_Getting_started.tex )........................
...........................................................................
........................... ( ./3_input_and_output_files.tex ).............
...........................................................................
.....................................................
 ( ./4_input_options.tex ).................................................
...........................................................................
...........................................................................
...........................................................................
...........................................................................
...........................................................................
...........................................................................
...........................................................................
...........................................................................
...........................................................................
...........................................................................
...........................................................................
...........................................................................
...........................................................................
...........................................................................
...........................................................................
...........................................................................
...........................................................................
...........................................................................
.................................................
 ( ./5_additional_input.tex )..............................................
...........................................................................
...........................................................................
...........................................................................
...........................................................................
...........................................................................
...........................................................................
.........................................................................
 ( ./6_prediction_phase_transitions.tex )..................................
...........................................................................
...........................................................................
...........................................................................
...........................................................................
...........................................................................
..................
WARNING: Could not find any file named: <plasTeX.TeXFragment object at
   0x107f4a2e0>
 )
WARNING: Could not find any file named: <plasTeX.TeXFragment object at
   0x107f4a580>
 )
WARNING: Could not find any file named: <plasTeX.TeXFragment object at
   0x107f4a640>
 ).........................................................................
.....
INFO: Directing output files to directory: uspex_manual_english.
INFO: Importing templates from /usr/local/lib/python3.9/site-
   packages/plasTeX/Renderers/PageTemplate
INFO: Importing templates from /usr/local/lib/python3.9/site-
   packages/plasTeX/Renderers/XHTML
INFO: Importing templates from /usr/local/lib/python3.9/site-
   packages/plasTeX/Renderers/XHTML/Themes/default
INFO: Using the imager "dvipng".
 [ sect0002.html
WARNING: Using default renderer for titlepage
WARNING: Using default renderer for hrule
WARNING: Using default renderer for vbox
 [ sect0003.html [ sect0004.htmlTraceback (most recent call last):
  File "/usr/local/bin/plastex", line 73, in <module>
    main(sys.argv)
  File "/usr/local/bin/plastex", line 53, in main
    run(filename, config)
  File "/usr/local/lib/python3.9/site-packages/plasTeX/Compile.py", line 114, in run
    renderer.render(document)
  File "/usr/local/lib/python3.9/site-packages/plasTeX/Renderers/PageTemplate/__init__.py", line 380, in render
    BaseRenderer.render(self, document)
  File "/usr/local/lib/python3.9/site-packages/plasTeX/Renderers/__init__.py", line 515, in render
    str(document)
  File "/usr/local/lib/python3.9/site-packages/plasTeX/Renderers/__init__.py", line 172, in __str__
    val = func(child)
  File "/usr/local/lib/python3.9/site-packages/plasTeX/Renderers/PageTemplate/__init__.py", line 88, in renderhtml
    template.expand(context, output)
  File "/usr/local/lib/python3.9/site-packages/plasTeX/Renderers/PageTemplate/simpletal/simpleTAL.py", line 702, in expand
    self.expandInline (context, outputFile, interpreter)
  File "/usr/local/lib/python3.9/site-packages/plasTeX/Renderers/PageTemplate/simpletal/simpleTAL.py", line 711, in expandInline
    Template.expandInline (self, context, outputFile, ourInterpreter)
  File "/usr/local/lib/python3.9/site-packages/plasTeX/Renderers/PageTemplate/simpletal/simpleTAL.py", line 627, in expandInline
    ourInterpreter.execute (self)
  File "/usr/local/lib/python3.9/site-packages/plasTeX/Renderers/PageTemplate/simpletal/simpleTAL.py", line 220, in execute
    self.commandHandler[cmnd[0]] (cmnd[0], cmnd[1])
  File "/usr/local/lib/python3.9/site-packages/plasTeX/Renderers/PageTemplate/simpletal/simpleTAL.py", line 466, in cmdEndTagEndScope
    self.file.write(str(resultVal))
  File "/usr/local/lib/python3.9/site-packages/plasTeX/Renderers/__init__.py", line 172, in __str__
    val = func(child)
  File "/usr/local/lib/python3.9/site-packages/plasTeX/Renderers/PageTemplate/__init__.py", line 88, in renderhtml
    template.expand(context, output)
  File "/usr/local/lib/python3.9/site-packages/plasTeX/Renderers/PageTemplate/simpletal/simpleTAL.py", line 702, in expand
    self.expandInline (context, outputFile, interpreter)
  File "/usr/local/lib/python3.9/site-packages/plasTeX/Renderers/PageTemplate/simpletal/simpleTAL.py", line 711, in expandInline
    Template.expandInline (self, context, outputFile, ourInterpreter)
  File "/usr/local/lib/python3.9/site-packages/plasTeX/Renderers/PageTemplate/simpletal/simpleTAL.py", line 627, in expandInline
    ourInterpreter.execute (self)
  File "/usr/local/lib/python3.9/site-packages/plasTeX/Renderers/PageTemplate/simpletal/simpleTAL.py", line 220, in execute
    self.commandHandler[cmnd[0]] (cmnd[0], cmnd[1])
  File "/usr/local/lib/python3.9/site-packages/plasTeX/Renderers/PageTemplate/simpletal/simpleTAL.py", line 466, in cmdEndTagEndScope
    self.file.write(str(resultVal))
  File "/usr/local/lib/python3.9/site-packages/plasTeX/Renderers/__init__.py", line 172, in __str__
    val = func(child)
  File "/usr/local/lib/python3.9/site-packages/plasTeX/Renderers/PageTemplate/__init__.py", line 88, in renderhtml
    template.expand(context, output)
  File "/usr/local/lib/python3.9/site-packages/plasTeX/Renderers/PageTemplate/simpletal/simpleTAL.py", line 702, in expand
    self.expandInline (context, outputFile, interpreter)
  File "/usr/local/lib/python3.9/site-packages/plasTeX/Renderers/PageTemplate/simpletal/simpleTAL.py", line 711, in expandInline
    Template.expandInline (self, context, outputFile, ourInterpreter)
  File "/usr/local/lib/python3.9/site-packages/plasTeX/Renderers/PageTemplate/simpletal/simpleTAL.py", line 627, in expandInline
    ourInterpreter.execute (self)
  File "/usr/local/lib/python3.9/site-packages/plasTeX/Renderers/PageTemplate/simpletal/simpleTAL.py", line 220, in execute
    self.commandHandler[cmnd[0]] (cmnd[0], cmnd[1])
  File "/usr/local/lib/python3.9/site-packages/plasTeX/Renderers/PageTemplate/simpletal/simpleTAL.py", line 466, in cmdEndTagEndScope
    self.file.write(str(resultVal))
  File "/usr/local/lib/python3.9/site-packages/plasTeX/Renderers/__init__.py", line 172, in __str__
    val = func(child)
  File "/usr/local/lib/python3.9/site-packages/plasTeX/Renderers/PageTemplate/__init__.py", line 88, in renderhtml
    template.expand(context, output)
  File "/usr/local/lib/python3.9/site-packages/plasTeX/Renderers/PageTemplate/simpletal/simpleTAL.py", line 702, in expand
    self.expandInline (context, outputFile, interpreter)
  File "/usr/local/lib/python3.9/site-packages/plasTeX/Renderers/PageTemplate/simpletal/simpleTAL.py", line 711, in expandInline
    Template.expandInline (self, context, outputFile, ourInterpreter)
  File "/usr/local/lib/python3.9/site-packages/plasTeX/Renderers/PageTemplate/simpletal/simpleTAL.py", line 627, in expandInline
    ourInterpreter.execute (self)
  File "/usr/local/lib/python3.9/site-packages/plasTeX/Renderers/PageTemplate/simpletal/simpleTAL.py", line 220, in execute
    self.commandHandler[cmnd[0]] (cmnd[0], cmnd[1])
  File "/usr/local/lib/python3.9/site-packages/plasTeX/Renderers/PageTemplate/simpletal/simpleTAL.py", line 466, in cmdEndTagEndScope
    self.file.write(str(resultVal))
  File "/usr/local/lib/python3.9/site-packages/plasTeX/Renderers/__init__.py", line 172, in __str__
    val = func(child)
  File "/usr/local/lib/python3.9/site-packages/plasTeX/Renderers/PageTemplate/__init__.py", line 88, in renderhtml
    template.expand(context, output)
  File "/usr/local/lib/python3.9/site-packages/plasTeX/Renderers/PageTemplate/simpletal/simpleTAL.py", line 702, in expand
    self.expandInline (context, outputFile, interpreter)
  File "/usr/local/lib/python3.9/site-packages/plasTeX/Renderers/PageTemplate/simpletal/simpleTAL.py", line 711, in expandInline
    Template.expandInline (self, context, outputFile, ourInterpreter)
  File "/usr/local/lib/python3.9/site-packages/plasTeX/Renderers/PageTemplate/simpletal/simpleTAL.py", line 627, in expandInline
    ourInterpreter.execute (self)
  File "/usr/local/lib/python3.9/site-packages/plasTeX/Renderers/PageTemplate/simpletal/simpleTAL.py", line 220, in execute
    self.commandHandler[cmnd[0]] (cmnd[0], cmnd[1])
  File "/usr/local/lib/python3.9/site-packages/plasTeX/Renderers/PageTemplate/simpletal/simpleTAL.py", line 299, in cmdRepeat
    result = self.context.evaluate (args[1], self.originalAttributes)
  File "/usr/local/lib/python3.9/site-packages/plasTeX/Renderers/PageTemplate/simpletal/simpleTALES.py", line 367, in evaluate
    return self.evaluatePath (expr)
  File "/usr/local/lib/python3.9/site-packages/plasTeX/Renderers/PageTemplate/simpletal/simpleTALES.py", line 420, in evaluatePath
    return self.traversePath (allPaths[0])
  File "/usr/local/lib/python3.9/site-packages/plasTeX/Renderers/PageTemplate/simpletal/simpleTALES.py", line 624, in traversePath
    elif (hasattr (val, "__call__")):result = val()
  File "/usr/local/lib/python3.9/site-packages/plasTeX/Packages/natbib.py", line 596, in citation
    return citet.citation(self, full=full, capitalize=capitalize)
  File "/usr/local/lib/python3.9/site-packages/plasTeX/Packages/natbib.py", line 453, in citation
    return self.numcitation()
  File "/usr/local/lib/python3.9/site-packages/plasTeX/Packages/natbib.py", line 578, in numcitation
    for i, item in enumerate(self.bibitems):
  File "/usr/local/lib/python3.9/site-packages/plasTeX/Packages/natbib.py", line 229, in bibitems
    items.sort(lambda x, y: int(x.ref) - int(y.ref))
TypeError: sort() takes no positional arguments
```

What can be wrong, if I put bibliography inside the tex-file in the following way:
```
\bibliography{reference.bib}{}
```

Hope you can help me with this.

**Comment by PatrickMassot** [comment] 2020-12-24 11:29
I'm sorry I'm answering late. I cannot help you since you didn't include a minimal example showing the issue. Since you are using an exotic obsolete LaTeX package, I would also need to get explanations about the expected output. 

Note that the error message points out a clear python2 to python3 transition bug. The method `list.sort` did change. If I were cornered into trying a blind fix, I would replace that line with `items.sort(key=lambda x: int(x.ref))`. But the proper way to handle this would be to understand what this line is meant to do, write a test triggering the bug and expressing the intended behavior and then fix it (and then drop natbib and bibtex and start using biblatex+biber of course).

**Comment by PatrickMassot** [comment] 2021-04-05 15:27
I'm closing this issue since you didn't provide the example that could have helped me fixing it, but feel free to reopen with the example.

**Closed by PatrickMassot** 2021-04-05 15:27 UTC

**Comment by samtsevich** [comment] 2021-06-03 17:18
Sorry for no reply, but the bug is still here.
I tried to debug it by myself and an empty field 'ref' inside 'bib item' object has been found.

You asked about the input .tex files - u can find them below to this comment.
Seems that it is easy to fix.
I hope you can do it.
[Archive.zip](https://github.com/plastex/plastex/files/6593290/Archive.zip)

**Comment by PatrickMassot** [comment] 2021-06-13 12:48
In my previous message I explained why the bug is still there, it's because you provided no example. Now you tried to provide the example but it's not a usable example. First your file doesn't compile because you forgot to include the pictures. And then it's way too big. If you want to see that bug fixed you need to provide a ten lines long TeX file demonstrating the bug, unless there is a very good reason why ten lines can't be enough.
